apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-{{ .Release.Name }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  S3_BUCKET_NAME: {{ .Values.configmap.S3_BUCKET_NAME }}
  REGION: {{ .Values.configmap.REGION }}
  RDS_CONNECTION_STRING: {{ .Values.configmap.RDS_CONNECTION_STRING }}
  