apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
      - prod.apurvamathur.me
      - app.prod.apurvamathur.me
      secretName: secret-tls
  rules:
  - host: app.prod.apurvamathur.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: webapp
          servicePort: 8080
